package mikufan.cx.project_vd_common_util.jackson.poc;

import lombok.ToString;

import java.beans.ConstructorProperties;

/**
 * when constructor with {@link ConstructorProperties} is not generated by lombok,
 * either we manually add a constructor with {@link ConstructorProperties} or compile with "-parameters" flag.
 */
@ToString(callSuper = true)
public class DummyHolder extends BaseDummyHolder<Dummy> {

  public DummyHolder(Dummy obj, String note) {
    super(obj, note);
  }
}
